services:
    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML
    
    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: ["@oc_platform.beta.html", "2016-01-02"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }